accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('mypage/<str:user_username>/', views.mypage, name="mypage"),   
    path('mypage/<str:user_username>/update/', views.update, name="update"),   
    path('mypage/<str:user_username>/delete/', views.delete, name="delete"),
    # 아이디 찾기
    path('findid/', views.findid, name="findid"),
    # path('testemail/', views.email, name="email"),
    # 비밀번호 초기화
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # 이메일 활성화
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

diarypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

dotori/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # 비밀번호 초기화 urls
    path('diaries/', include('diaries.urls')),
    path('friends/', include('friends.urls')),
]

# MEDIA_URL에 대한 설정 추가
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return 'user_{0}/{1}'.format(instance.username, filename)

class User(AbstractUser):
    nickname = models.CharField(max_length=10)
    profile_image = models.ImageField(upload_to=user_directory_path, null=True, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'email',
            'nickname',
            'profile_image',
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            'email',
            'nickname',
            'profile_image',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import User
from .forms import CustomUserCreationForm, CustomUserChangeForm

from django.core.mail import EmailMessage
from django.contrib import messages
from django.conf import settings

# 회원가입
def signup(request):
    if request.user.is_authenticated:
        return redirect('diaries:index')
    
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            # user = form.save()
            # auth_login(request, user)
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return render(request, 'accounts/emailsent.html')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

# 활성화 이메일 보내기
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

from .tokens import account_activation_token

def activateEmail(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('accounts/activateaccount.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        return render(request, 'accounts/emailsent.html')
    else:
        redirect('accounts:singup')

from django.contrib.auth import get_user_model

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        # messages.success(request, '인증이 성공했습니다. 이제 로그인이 가능합니다.')
        return redirect('accounts:login')
    else:
        # messages.error(request, '인증 링크가 유효하지 않습니다. 다른 이메일로 재시도해보세요.')
    
        return redirect('diaries:index')
    
# 로그인
def login(request):
    if request.user.is_authenticated:
        return redirect('diaries:index')
    
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('diaries:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)
    
# 로그아웃
@login_required
def logout(request):
    auth_logout(request)
    return redirect('diaries:index')

# 마이페이지 (로그인되어야만 입장 가능)
@login_required
def mypage(request, user_username):
    return render(request, 'accounts/mypage.html')

# 회원 정보 수정, 비밀번호 변경까지 함께
@login_required
def update(request, user_username):
    if request.method == "POST":
        form_user = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        form_password = PasswordChangeForm(request.user, request.POST)
        if form_user.is_valid() and form_password.is_valid():
            form_user.save()
            user = form_password.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:mypage', user.username)
    else:
        form_user = CustomUserChangeForm(instance=request.user)
        form_password = PasswordChangeForm(request.user)
    context = {
        'form_user' : form_user,
        'form_password' : form_password,
    }
    return render(request, 'accounts/update.html', context)

# 회원 탈퇴
@login_required
def delete(request, user_username):
    request.user.delete()
    return redirect('diaries:index')

def findid(request):
    context = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            if user is not None:
                method_email = EmailMessage(
                    'Your ID is in the email',
                    str(user.username),
                    settings.EMAIL_HOST_USER,
                    [email],
                )
                method_email.send(fail_silently=False)
                print('success', email)
                return render(request, 'accounts/emailsent.html')
            
        except:
            print('fail', email)
            messages.info(request, 'There is no username along with the email')
    context = {}
    return render(request, 'accounts/findid.html', context)

# 이메일 보내기 테스트
# from django.core.mail import send_mail
# from django.conf import settings
# from django.shortcuts import redirect

# def email(request):
#     subject = 'Thank you for registering to our site'
#     message = 'It means a world to us'
#     email_from = settings.EMAIL_HOST_USER
#     recipient_list = ['example@gmail.com']
#     send_mail(subject, message, email_from, recipient_list, fail_silently=False)
#     return redirect('accounts:findid')

accounts/templates/accounts/activateaccount.html
{% autoescape off %}
{{ user }}님!

아래 link를 눌러 등록을 마치세요.

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/emailsent.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>이메일을 전송했습니다.</h1>

</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/findid.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>아이디 찾기</h1>

<form action="{% url 'accounts:findid' %}" method="POST">
    {% csrf_token %}
    Email: <input type="email" name='email'>
    <input type="submit" value="확인">
</form>

</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/idsent.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>아이디를 이메일로 전송했습니다.</h1>

</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>로그인</h1>

<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
</form>

<a href="{% url "accounts:findid" %}">아이디 찾기</a>
<a href="{% url "accounts:password_reset" %}">비밀번호 찾기</a>
{% comment %} <a href="{% url "accounts:email" %}">이메일 테스트</a> {% endcomment %}



</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/mypage.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>마이 페이지</h1>
  <p><b>♡환영합니다♡</b></p>
  {% if user.profile_image %}
    <img src="{{ user.profile_image.url }}" alt="user profile image" style="width:300px; object-fit:cover;">
  {% else %}
    <img src="{% static "img/dotori_logo.png" %}" alt="user default image" style="width:300px; object-fit:cover;">
  {% endif %}
  <p>{{ user.nickname }}</p>
  <ul>
    <li>
        <a href="{% url 'accounts:update' user.username %}">회원정보 변경</a>
    </li>
    <li>
        <a href="{% url 'accounts:delete' user.username %}">회원탈퇴</a>
    </li>
  </ul>
</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>회원가입</h1>

  <form action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="가입하기">
  </form>
</main>
{% endblock content %}
{% block js %}{% endblock js %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock styles %}
{% block content %}
<main class="index-main">
  <h1>회원정보 변경</h1>
  <form action="{% url 'accounts:update' user.username %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form_user.as_p }}
      {{ form_password.as_p }}
      <input type="submit" value="변경하기">
  </form>
</main>
{% endblock content %}
{% block js %}{% endblock js %}