accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('mypage/<str:user_username>/', views.mypage, name="mypage"),   
    path('mypage/<str:user_username>/update/', views.update, name="update"),   
    path('mypage/<str:user_username>/delete/', views.delete, name="delete"),
    # 아이디 찾기
    path('findid/', views.findid, name="findid"),
    # path('testemail/', views.email, name="email"),
    # 비밀번호 초기화
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # 이메일 활성화
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

diaries/urls.py
from django.urls import path
from . import views

app_name = "diaries"

urlpatterns = [
    path('', views.index, name="index"),
    path('create-diary/', views.creatediary, name="create_diary"),
    path('my-diary/', views.mydiary, name="my_diary"),
    path('<int:diary_pk>/', views.notelist, name="note_list"),  # 다이어리의 모든 노트를 보여주는 페이지
    path('<int:diary_pk>/note/<int:note_pk>/', views.notedetail, name="note_detail"),  # 특정 노트 세부정보
    path('<int:diary_pk>/create/', views.createnote, name='create_note'),
    path('<int:diary_pk>/<int:note_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:diary_pk>/<int:note_pk>/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:diary_pk>/<int:note_pk>/likes/', views.likes, name='likes'),
    path('<int:diary_pk>/note/<int:note_pk>/delete/', views.delete_note, name='delete_note'),
    path('diary/<int:diary_pk>/note/<int:note_pk>/edit/', views.editnote, name='edit_note'),
]




# from django.urls import path
# from . import views

# app_name = "diaries"

# urlpatterns = [
#   path('', views.index, name="index"),
#   path('create-diary/', views.creatediary, name="create_diary"),
#   path('my-diary/', views.mydiary, name="my_diary"),
#   # path('<int:diary_pk>/', views.notelist, name="note_list"),
#   path('<int:diary_pk>/create/', views.createnote, name='create_note'),
#   path('<int:diary_pk>/', views.notedetail, name="note_detail"),
#   path('<int:diary_pk>/<int:note_pk>/comments/', views.comments_create, name='comments_create'),
#   path('<int:diary_pk>/<int:note_pk>/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
#   path('<int:diary_pk>/<int:note_pk>/likes/', views.likes, name='likes'),
# ]

diarypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

dotori/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # 비밀번호 초기화 urls
    path('diaries/', include('diaries.urls')),
    path('friends/', include('friends.urls')),
]

# MEDIA_URL에 대한 설정 추가
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path
from . import views

app_name = "friends"

urlpatterns = [
  path('add-friend', views.addfriend, name="add_friend"),
  path('search-friend/', views.searchfriend, name="search_friend"),
  path('my-friends/', views.myfriends, name="my_friends"),
  path('reject-friend/<int:friend_id>/', views.rejectfriend, name="reject_friend"),
  path('accept-friend/<int:friend_id>/', views.acceptfriend, name="accept_friend"),
  path('friend-request-cancel/<int:friend_id>/', views.cancelfriend, name='friend_request_cancel'),
  path('delete-friend/<int:friend_id>/', views.deletefriend, name='delete_friend'),
]

templates/_navbar.html
<nav class="navbar">
  <div class="navbar__logo">도토리</div>
  <ul class="navbar__menu">
    <a href="{% url 'diaries:index' %}">
      <li class="{% if request.path == '' %}current-page{% endif %}">HOME</li>
    </a>    
    {% if request.user.is_authenticated %}
    <a href="{% url 'diaries:create_diary' %}">
      <li class="{% if request.path == '/diaries/add-diary/' %}current-page{% endif %}">다이어리생성</li>
    </a>
    <a href="{% url 'diaries:my_diary' %}">
      <li class="{% if request.path == '/diaries/my-diary/' %}current-page{% endif %}">내 다이어리</li>
    </a>
    <a href="{% url 'friends:add_friend' %}">
      <li class="{% if request.path == '/friends/add-friend/' %}current-page{% endif %}">친구추가</li>
    </a>
    <a href="{% url 'friends:my_friends' %}">
      <li class="{% if request.path == '/friends/my-friends/' %}current-page{% endif %}">친구목록</li>
    </a>
    <a href="{% url 'accounts:mypage' user.username%}">
      <li class="{% if request.path == '/accounts/my-page/' %}current-page{% endif %}">마이페이지</li>
    </a>
    <a href="{% url 'accounts:logout' %}">
      <li>로그아웃</li>
    </a>
    {% else %}
    <a href="{% url 'accounts:signup' %}">
      <li class="{% if request.path == '/accounts/sign-up/' %}current-page{% endif %}">회원가입</li>
    </a>
    <a href="{% url 'accounts:login' %}">
      <li class="{% if request.path == '/accounts/log-in/' %}current-page{% endif %}">로그인</li>
    </a>
    {% endif %}
  </ul>
  
  <a href="#" class="navbar__toggleBtn">
    <i class="fa-solid fa-bars fa-xl" style="color: #F5F5F5;"></i>
  </a>
</nav>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> {% block title %}{% endblock title %} </title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  {% block styles %}{% endblock styles %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
  {% include "_navbar.html" %}
  {% block content %}{% endblock content %}

  <script src="{% static 'js/navbar.js' %}"></script>
  {% block js %}{% endblock js %}
</body>
</html>